[package]
name = "thermite"
version = "0.1.0"
authors = ["Andrew Bastien <volundmush@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.2", features = ["full"]}
tokio-util = {version = "0.6", features = ["codec"]}
tokio-rustls = "0.22"
rand = "0.8"
bytes = "1.0"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
chrono = "0.4"
tungstenite = "0.12"
tokio-tungstenite = {version = "0.13", features = ["stream"]}
regex = "1.3"
async-trait = "0.1"
futures = "0.3"